language: dart
sudo: required
dist: trusty
dart:
  - stable
  - beta
  - dev
before_script:
  # Simple test
  - pub run chrome_travis:env_rc -v
  - source $(pub run chrome_travis:env_rc -v)
script:
  - tool/travis.sh