name: tekartik_travis_test
version: 0.0.1
environment:
  sdk: '>=1.24.0 <2.0.0'

dev_dependencies:
  test: any
  dev_test: any
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart1
    version: '>=0.1.3'