name: tekartik_travis_test
version: 0.1.0

environment:
  sdk: '>=2.5.0-dev <3.0.0'

dev_dependencies:
  test: any
  dev_test: any
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
    version: '>=0.1.3'